name: sweeper
repository: https://github.com/thassio/sweeper

packages:
  - .
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- dart analyze
    description: Run `dart analyze` in all packages.

  test:
    run: dart run melos exec --fail-fast --concurrency=1 -- flutter test
    description: Run tests in all packages.
    packageFilters:
      dirExists: test

  format:
    run: melos exec -- dart format .
    description: Format all packages.
