name: sweeper
description: Reversed Minesweeper - a Flutter board game.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.13.0
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  easy_localization: ^3.0.7
  get_it: ^8.0.3
  go_router: ^15.1.2
  sweeper_auth:
    path: packages/sweeper_auth
  sweeper_core:
    path: packages/sweeper_core
  sweeper_game:
    path: packages/sweeper_game
  sweeper_l10n:
    path: packages/sweeper_l10n
  sweeper_settings:
    path: packages/sweeper_settings
  sweeper_theme:
    path: packages/sweeper_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  melos: ^6.3.0
  mocktail: ^1.0.4
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - packages/sweeper_l10n/assets/translations/
